version: '3'

services:
        nginx:
                image: nginx:1.13
                ports:
                        - 80:80
                volumes:
                        - .src:/usr/share/nginx/html
                        - .src:/usr/share/nginx/html
                depends_on:
                        - php

                php:
                        image: php:7.2-fpm
                        volumes:
                                - ./src:/usr/share/nginx/html
                          
